kafka:
  broker:
    user: confluent
    group: confluent
    config_file: /etc/kafka/server.properties
    logging_config_file: /etc/kafka/server.logging.properties
    systemd_file: /lib/systemd/system/confluent-kafka.service
    service_name: confluent-kafka
    rootdir: /var/lib/kafka
    datadir:
      - /var/lib/kafka/data
    environment:
      KAFKA_HEAP_OPTS: "-Xms4g -Xmx4g"
      LOG_DIR: /var/log/kafka
      JMX_PORT: 9999
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9999"
      KAFKA_OPTS: " -javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent-0.3.1.jar=7071:/etc/jmx_exporter/kafka.yml"
    systemd:
      enabled: yes
      state: started
      LimitNOFILE: 500000
      TimeoutStopSec: 300
      RestartSec: 5
    config:
      auto.create.topics.enable: true
      compression.type: "snappy"
      confluent.support.metrics.enable: false
      controlled.shutdown.enable: true
      default.replication.factor: 2
      group.initial.rebalance.delay.ms: 0
      log.retention.check.interval.ms: 300000
      log.retention.hours: 4368
      log.segment.bytes: 1073741824
      message.max.bytes: 16777216
      min.insync.replicas: 2
      num.io.threads: 16
      num.network.threads: 8
      num.partitions: 1
      num.recovery.threads.per.data.dir: 2
      offsets.retention.minutes: 10080
      offsets.topic.replication.factor: 3
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      socket.send.buffer.bytes: 102400
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 2
      zookeeper.connection.timeout.ms: 12000
