schema:
  registry:
    user: confluent
    group: confluent
    config_file: /etc/kafka/schema-registry.properties
    logging_config_file: /etc/kafka/schema-registry.logging.properties
    systemd_file: /lib/systemd/system/confluent-schema-registry.service
    service_name: confluent-schema-registry
    config:
      listeners: http://0.0.0.0:8081
      kafkastore.topic: _schemas
      debug: false
      access.control.allow.methods: "GET,POST,PUT,OPTIONS"
      access.control.allow.origin: "*"
    environment:
      SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
      LOG_DIR: /var/log/schema-registry
      JMX_PORT: 7777
      SCHEMA_REGISTRY_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=7777"
    systemd:
      enabled: yes
      state: started
      LimitNOFILE: 128000
      TimeoutStopSec: 300
      RestartSec: 5
