{
 "title": "Kafka Connect",
 "time": { "from": "now-60m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Sink  Record  Send Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_sink_task_metrics_sink_record_send_rate"
    }
   ]
  },
  {
   "title": "Debezium Rows Scanned",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_rowsscanned",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Debezium Binlog Position",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_binlogposition",
     "legendFormat": "{{server}} -> {{instance}}"
    }
   ]
  },
  {
   "title": "Debezium Poll Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_source_task_metrics_source_record_poll_rate",
     "legendFormat": "{{connector}} -> {{instance}}"
    }
   ]
  },
  {
   "title": "Connect Outgoing Byte Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_outgoing_byte_rate",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Connect Workers Incoming Byte Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_incoming_byte_rate",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Debezium Connected",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_connected",
     "legendFormat": "{{server}} -> {{instance}}"
    }
   ]
  },
  {
   "title": "Connectors Rebalances",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_completed_rebalances_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Connect Sync Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_coordinator_metrics_sync_rate",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}