{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-60m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Broker State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_brokerstate",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Controller",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum (kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)"
    }
   ]
  },
  {
   "title": "ISR Delta",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (kafka_server_replicamanager_isrexpands_total) - sum( kafka_server_replicamanager_isrshrinks_total)"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount)"
    }
   ]
  },
  {
   "title": "Messages In Total per Topic",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}