global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# No alerting on Prometheus => Will be set on Grafana
# rule_files:
#   - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'kafka_brokers'
    scrape_interval: 15s
    static_configs:
      - targets: ['kafka-jmx-exporter:8080']

  - job_name: 'nodeexporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['nodeexporter:9100']

  # - job_name: 'cadvisor'
  #   scrape_interval: 15s
  #   static_configs:
  #     - targets: ['localhost:8083']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
