---
- name: create prometheus system group
  group:
    name: prometheus
    system: yes

- name: create prometheus system user
  user:
    name: prometheus
    system: yes
    shell: "/sbin/nologin"
    group: prometheus
    createhome: no

- name: Create prometheus directory structure
  file: >
    state=directory
    path={{ item }}
    owner=prometheus
    group=prometheus
  with_items:
    - "/opt/prometheus"
    - "/etc/prometheus"
    - "/etc/prometheus/rules"
    - "/var/lib/prometheus"
    - "/var/log/prometheus"
    - "/opt/prometheus/current"

- name: Download component binaries
  get_url:
    url: "{{item}}"
    dest: "/opt/prometheus/current"
  with_items:
    - "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    - "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    - "https://github.com/prometheus/pushgateway/releases/download/v{{ pushgateway_version }}/pushgateway-{{ pushgateway_version }}.linux-amd64.tar.gz"
    - "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

- name: Unarchive component tarballs
  unarchive:
    copy: no
    src: "/opt/prometheus/current/{{item}}.tar.gz"
    dest: "/opt/prometheus/current"
    creates: "/opt/prometheus/current/{{item}}"
  with_items:
  - "prometheus-{{ prometheus_version }}.linux-amd64"
  - "node_exporter-{{ node_exporter_version }}.linux-amd64"
  - "alertmanager-{{ alertmanager_version }}.linux-amd64"
  - "pushgateway-{{ pushgateway_version }}.linux-amd64"



- name: Import Grafana GPG signing key [Debian/Ubuntu]
  apt_key:
    url: "https://packagecloud.io/gpg.key"
    state: present
    validate_certs: false
  register: _add_apt_key
  until: _add_apt_key is succeeded
  retries: 5
  delay: 2

- name: Add Grafana repository [Debian/Ubuntu]
  apt_repository:
    repo: deb https://packagecloud.io/grafana/stable/debian/ stretch main
    state: present
    update_cache: true
  register: _update_apt_cache
  until: _update_apt_cache is succeeded
  retries: 5
  delay: 2

- name: Install grafana
  apt: name=grafana state=latest update_cache=true

- name: Create systemd service units
  template:
    src: etc/systemd/system/{{item}}.service.j2
    dest: /etc/systemd/system/{{item}}.service
    owner: root
    group: root
    mode: 0644
  with_items:
    - prometheus
    - node_exporter
    - pushgateway
    - alertmanager

- name: Copy prometheus config
  template:
    src: "etc/prometheus/prometheus.yml.j2"
    dest: "/etc/prometheus/prometheus.yml"
    mode: 0644

# - name: Create grafana config from ini config file
#   notify: restart grafana
#   template: src=etc/grafana/grafana.ini dest=/etc/grafana/grafana.ini

- name: Create Grafana Provisioning directories
  file:
    path: "{{item}}"
    state: directory
    mode: 0750
    owner: grafana
    group: grafana
  with_items:
    - /etc/grafana/provisioning/datasources
    - /etc/grafana/provisioning/dashboards
    - /var/lib/grafana/dashboards
  become: True

- name: Copy Prometheus Datasource config
  copy:
    src: prometheus_datasource.yaml
    dest: /etc/grafana/provisioning/datasources/prometheus.yaml
    mode: 0640
    owner: grafana
    group: grafana
  become: True
  notify: restart grafana

- name: Copy Grafana Dashboards
  copy:
    src: "{{item}}"
    dest: /var/lib/grafana/dashboards/
    mode: 0640
    owner: grafana
    group: grafana
  with_fileglob:
    - dashboards/*.json
  become: True

- name: Copy Grafana config adding the Dashboards
  copy:
    src: dashboards/kafka.yaml
    dest: /etc/grafana/provisioning/dashboards/kafka.yaml
    mode: 0640
    owner: grafana
    group: grafana
  become: True

- name: Copy Prometheus Rules
  copy: src={{item}} dest=/etc/prometheus/{{item}}
  with_items:
    - alert.rules
  notify: reload prometheus

- name: Create directory size cronjob
  copy:
    dest: /etc/cron.d/directory_size
    mode: 0644
    content: |
      */5 * * * * root du -sb /var/log /var/cache/apt /var/lib/prometheus | sed -ne 's/^\([0-9]\+\)\t\(.*\)$/node_directory_size_bytes{directory="\2"} \1/p' > /var/lib/node_exporter/textfile_collector/directory_size.prom.$$ && mv /var/lib/node_exporter/textfile_collector/directory_size.prom.$$ /var/lib/node_exporter/textfile_collector/directory_size.prom

- name: Start services
  systemd: name={{item}} state=started enabled=yes
  with_items:
    - prometheus
    - alertmanager

- name: Restart Grafana
  systemd: name={{item}} state=restarted enabled=yes
  with_items:
    - grafana-server

- meta: flush_handlers
